<a href="https://colab.research.google.com/github/jvallalta/ia3/blob/main/Intro_convolucion_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Cargamos las librerias
import numpy as np
import torch
import torchvision
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [4]:
input_1d = torch.tensor([1,2,3,4,5,6,7,8,9, 10], dtype=torch.float)
input_1d.shape

torch.Size([10])

In [6]:
input_1d = input_1d.unsqueeze(0).unsqueeze(0)
input_1d.shape

torch.Size([1, 1, 10])

In [8]:
cnn1d_1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=1 )


In [9]:
print(cnn1d_1(input_1d).shape)
print(cnn1d_1(input_1d))

torch.Size([1, 1, 8])
tensor([[[-1.1439, -1.8429, -2.5419, -3.2409, -3.9399, -4.6389, -5.3379,
          -6.0369]]], grad_fn=<SqueezeBackward1>)


In [11]:
cnn1d_2 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=2 )
print(cnn1d_2(input_1d).shape)
print(cnn1d_2(input_1d))

torch.Size([1, 1, 4])
tensor([[[0.8835, 0.6719, 0.4603, 0.2487]]], grad_fn=<SqueezeBackward1>)


In [12]:
cnn1d_3 = nn.Conv1d(in_channels=1, out_channels=5, kernel_size=3, stride=1)
print(cnn1d_3(input_1d).shape)
print(cnn1d_3(input_1d))

torch.Size([1, 5, 8])
tensor([[[-1.1465, -1.4818, -1.8171, -2.1524, -2.4877, -2.8230, -3.1583,
          -3.4936],
         [-0.6822, -0.9996, -1.3169, -1.6342, -1.9516, -2.2689, -2.5862,
          -2.9036],
         [ 0.3569,  0.3495,  0.3420,  0.3346,  0.3271,  0.3197,  0.3122,
           0.3048],
         [-1.7229, -2.3661, -3.0094, -3.6526, -4.2958, -4.9391, -5.5823,
          -6.2256],
         [-2.0663, -3.1798, -4.2933, -5.4068, -6.5203, -7.6338, -8.7474,
          -9.8609]]], grad_fn=<SqueezeBackward1>)


In [15]:
cnn1d_4 = nn.Conv1d(in_channels=1, out_channels=5, kernel_size=3, stride=2, padding=1 )
print(cnn1d_4(input_1d).shape)
print(cnn1d_4(input_1d))

torch.Size([1, 5, 5])
tensor([[[ 0.9320,  2.1710,  3.4101,  4.6492,  5.8882],
         [-1.3820, -1.6559, -1.9298, -2.2037, -2.4776],
         [ 0.8200,  1.8808,  2.9416,  4.0024,  5.0632],
         [ 0.0587, -0.0389, -0.1365, -0.2341, -0.3317],
         [ 0.0598, -0.7403, -1.5404, -2.3404, -3.1405]]],
       grad_fn=<SqueezeBackward1>)


In [17]:
input_2d = torch.tensor([[1,2,3,4,5,6,7,8,9, 10], [1,2,3,4,5,6,7,8,9, 10]] , dtype=torch.float)
input_2d.shape

torch.Size([2, 10])

In [18]:
input_2d = input_2d.unsqueeze(0)
input_2d.shape

torch.Size([1, 2, 10])

In [24]:
cnn1d_5 = nn.Conv1d(in_channels=2, out_channels=5, kernel_size=3, stride=1, padding=1 )
print(cnn1d_5(input_2d).shape)
print(cnn1d_5(input_2d))

torch.Size([1, 5, 10])
tensor([[[-4.5149e-01, -1.5633e+00, -2.6752e+00, -3.7870e+00, -4.8989e+00,
          -6.0107e+00, -7.1226e+00, -8.2345e+00, -9.3463e+00, -8.7806e+00],
         [-2.4606e-01, -3.2843e-01, -4.1080e-01, -4.9318e-01, -5.7555e-01,
          -6.5792e-01, -7.4029e-01, -8.2266e-01, -9.0503e-01, -3.9816e+00],
         [-4.5351e-01, -8.5880e-01, -1.2641e+00, -1.6694e+00, -2.0747e+00,
          -2.4800e+00, -2.8853e+00, -3.2906e+00, -3.6959e+00, -8.8352e-03],
         [-6.3470e-02,  3.0266e-01,  6.6878e-01,  1.0349e+00,  1.4010e+00,
           1.7672e+00,  2.1333e+00,  2.4994e+00,  2.8655e+00,  4.1145e+00],
         [ 9.1639e-02,  8.0193e-02,  6.8746e-02,  5.7300e-02,  4.5854e-02,
           3.4408e-02,  2.2961e-02,  1.1515e-02,  6.9022e-05, -1.1202e+00]]],
       grad_fn=<SqueezeBackward1>)


In [25]:
input_2d_img = torch.tensor([[[1,2,3,4,5,6,7,8,9, 10], [1,2,3,4,5,6,7,8,9, 10], [1,2,3,4,5,6,7,8,9, 10]], [[1,2,3,4,5,6,7,8,9, 10], [1,2,3,4,5,6,7,8,9, 10], [1,2,3,4,5,6,7,8,9, 10]], [[1,2,3,4,5,6,7,8,9, 10], [1,2,3,4,5,6,7,8,9, 10], [1,2,3,4,5,6,7,8,9, 10]]] , dtype=torch.float)
input_2d_img.shape

torch.Size([3, 3, 10])

In [26]:
input_2d_img = input_2d_img.unsqueeze(0)
input_2d_img.shape

torch.Size([1, 3, 3, 10])

In [31]:
cnn2d_1 = nn.Conv2d(in_channels=3, out_channels=5, kernel_size=3, stride=1, padding=1 )
print(cnn2d_1(input_2d_img).shape)
print(cnn2d_1(input_2d_img))

torch.Size([1, 5, 3, 10])
tensor([[[[-0.2005, -0.6111, -1.0216, -1.4322, -1.8427, -2.2533, -2.6638,
           -3.0744, -3.4850, -4.9439],
          [-0.4994, -1.0800, -1.6607, -2.2414, -2.8220, -3.4027, -3.9834,
           -4.5640, -5.1447, -3.8503],
          [-0.2564, -0.4563, -0.6561, -0.8559, -1.0558, -1.2556, -1.4554,
           -1.6553, -1.8551, -0.8892]],

         [[-0.6749, -1.6212, -2.5675, -3.5139, -4.4602, -5.4066, -6.3529,
           -7.2992, -8.2456, -7.1272],
          [-0.5449, -1.5165, -2.4882, -3.4599, -4.4316, -5.4033, -6.3750,
           -7.3467, -8.3184, -7.7193],
          [-0.2197, -0.8594, -1.4991, -2.1388, -2.7786, -3.4183, -4.0580,
           -4.6977, -5.3374, -6.2780]],

         [[ 0.2704,  0.7201,  1.1697,  1.6194,  2.0690,  2.5187,  2.9683,
            3.4180,  3.8676,  4.2483],
          [ 0.5349,  0.9263,  1.3178,  1.7093,  2.1007,  2.4922,  2.8837,
            3.2751,  3.6666,  2.3816],
          [ 0.2864,  0.2085,  0.1305,  0.0525, -0.0255, -0.1035, -