<a href="https://colab.research.google.com/github/jvallalta/ia3/blob/main/LSTM_keras_basico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [4]:
inputs = tf.random.normal([32,10,8])

In [6]:
from keras.layers import LSTMCell, LSTM

In [7]:
lstm = tf.keras.layers.LSTM(4)

In [8]:
output = lstm(inputs)

In [10]:
print(output.shape)

(32, 4)


In [11]:
lstm = tf.keras.layers.LSTM(4, return_sequences=True, return_state=True)

In [12]:
secuencia, memoria, estado = lstm(inputs)

In [13]:
print(secuencia.shape)

(32, 10, 4)


In [14]:
print(memoria.shape)

(32, 4)


In [15]:
print(estado.shape)

(32, 4)


Ejercicio 1

In [37]:
import numpy as np
secuencia = tf.random.normal([1,10,2])


In [38]:
secuencia

<tf.Tensor: shape=(1, 10, 2), dtype=float32, numpy=
array([[[-0.18677881,  2.114399  ],
        [ 0.24520142,  2.0664635 ],
        [ 1.1847506 , -1.473997  ],
        [ 0.86762476, -0.30733934],
        [-1.3090165 , -1.3256246 ],
        [-1.4213912 , -1.4124634 ],
        [ 0.16435707,  0.3835207 ],
        [-2.5825322 , -0.25591847],
        [ 1.4195796 , -2.019553  ],
        [-0.42746076,  1.6398534 ]]], dtype=float32)>

In [42]:
from keras.models import Sequential
from keras.layers import Dense
modelo = Sequential()
modelo.add(LSTM(4, input_shape=(10,2), return_sequences=True))
modelo.add(LSTM(4, input_shape=(10,2)))
modelo.add(Dense(1))


In [43]:
resultado = modelo(secuencia)

In [44]:
resultado

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.00461306]], dtype=float32)>